### ISSUE TITLE
Oobabooga's Text-Generation-WebUI docker

### ISSUE THREAD

**Issue by mongolu** [Josh-XT/AGiXT#939]
### Feature/Improvement Description

I've made a Dockerfile for Oobabooga's Text Gen UI which uses  One-Click-Installers also from Ooba.

It's running update.sh at every restart of the container, so it keeps the image fresh.

And this also means that no special attention is needed in AGiXT.sh to update it.

I've been using it for almost a month now and all is working w/o any issues.

Do you want to take a look ?

### Proposed Solution

New auto-updatable Dockerfile for Oobabooga's Text-Generation-WebUI

### Acknowledgements

- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for everyone to understand why this feature request is needed in AGiXT.

**Comment by Josh-XT** [comment]
That would be great, the current way is not great for exactly that reason.  It might be worth even contributing to Ooba repo as a better alternative to their dockerfile.

**Comment by mongolu** [comment]
Here it is.

There is a need for two ENV vars when launching their webui.py, one for choosing GPU choice and  one for not launching server.py (if it's the build phase from dockerfile, it shouldn't).

I've opened an [issue ](https://github.com/oobabooga/one-click-installers/issues/108)for these (with a PR), but didn't pass.

Current variant here uses `sed` to monkey patch these checkpoints (not too happy for this, but it gets the job done).
If those two ENV vars would be included in the future on their side, it would be nicer, indeed.

Until then, `Dockerfile-text-generation-webui`:

```
FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y \
    gcc g++ build-essential cmake wget curl aria2 git

RUN mkdir -p /app

WORKDIR /app

ENV OOBABOOGA_FLAGS=${OOBABOOGA_FLAGS}
# ENV CUDA_VISIBLE_DEVICES=1,0 # personal choice
# ENV OOBABOOGA_INSTALL_GPU_CHOICE=a # ENV var for gpuchoice in webui.py
# ENV OOBABOOGA_LAUNCH_AFTER_INSTALL=no # ENV var for not launching server.py, in webui.py

RUN aria2c -x4 https://developer.download.nvidia.com/compute/cuda/11.7.0/local_installers/cuda_11.7.0_515.43.04_linux.run && \
    /bin/bash /app/cuda_11.7.0_515.43.04_linux.run --silent --toolkit && \
    rm -rf /app/cuda_11.7.0_515.43.04_linux.run

RUN git clone https://github.com/oobabooga/one-click-installers

# https://developer.nvidia.com/cuda-gpus
# for a rtx 2060: ARG TORCH_CUDA_ARCH_LIST="7.5"
ARG TORCH_CUDA_ARCH_LIST="6.0;6.1;7.0;7.5;8.0;8.6+PTX"

# monkey-patch until ENV vars would be accepted
RUN /bin/bash -c "sed -i 's/gpuchoice = input(\"Input> \").lower()/gpuchoice = \"a\"/g' /app/one-click-installers/webui.py"
RUN /bin/bash -c "sed -i 's/    run_cmd(f\"python server.py/#    run_cmd(f\"python server.py/g' /app/one-click-installers/webui.py"

RUN /bin/bash /app/one-click-installers/start_linux.sh

RUN /bin/bash -c "/app/one-click-installers/installer_files/conda/bin/conda init bash"

RUN cd /app/one-click-installers/installer_files/env/lib/python3.10/site-packages/bitsandbytes && \
    cp libbitsandbytes_cuda117.so libbitsandbytes_cpu.so

ENV OOBABOOGA_LAUNCH_AFTER_INSTALL=

RUN /app/one-click-installers/installer_files/conda/bin/conda init bash

RUN echo "conda activate /app/one-click-installers/installer_files/env" >> ~/.bashrc

# monkey-patch until ENV vars would be accepted
RUN /bin/bash -c "sed -i 's/#    run_cmd(f\"python server.py/    run_cmd(f\"python server.py/g' /app/one-click-installers/webui.py"

ENTRYPOINT /bin/bash /app/one-click-installers/update_linux.sh && /bin/bash /app/one-click-installers/start_linux.sh

#rm -rf build.log && docker-compose -f docker-compose-local-nvidia.yml build --no-cache 2>&1 | tee -a build.log

```

And my lines for TGWUI from `docker-compose-local-nvidia.yml`:
```
  text-generation-webui:
    build:
      context: .
      dockerfile: Dockerfile-text-generation-webui
      args:
        # specify which cuda version your card supports: https://developer.nvidia.com/cuda-gpus
        TORCH_CUDA_ARCH_LIST: ${TORCH_CUDA_ARCH_LIST:-7.5}
    environment:
      - OOBABOOGA_FLAGS=${CLI_ARGS}
    ports:
      - "${HOST_PORT:-7860}:${CONTAINER_PORT:-7860}"
      - "${HOST_API_PORT:-5000}:${CONTAINER_API_PORT:-5000}"
      - "${HOST_API_STREAM_PORT:-5005}:${CONTAINER_API_STREAM_PORT:-5005}"
      - "${HOST_API_OPENAI_PORT:-5001}:${CONTAINER_API_OPENAI_PORT:-5001}"
    stdin_open: true
    tty: true
    volumes:
      - /home/mihai/LLMmodels:/app/one-click-installers/text-generation-webui/models/LLMmodels:rw
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
```
